# Generated by Django 4.2.5 on 2023-10-03 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_pedido',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='menus',
            field=models.ManyToManyField(through='pedido.DetallePedido', to='menu.menu'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
