# Generated by Django 4.2.5 on 2023-10-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_rename_fecha_pedido_pedido_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
